name: rule-ci-lab
on:
  pull_request:
    branches:
      - develop
jobs:
  check-ci-sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Instalando Dependências
        run: npm install jest @types/jest sonar-scanner --only-dev      
      - name: Executando Teste  
        run: npm run test
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}