name: Node.js CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./calcjs  
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Instalando Dependências
        run: npm install jest @types/jest sonar-scanner --only-dev      
      - name: Executando Teste  
        run: npm run test